# Generated by Django 3.2.23 on 2024-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlyRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyregister',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email Address'),
        ),
    ]
